name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the first Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/api-add:latest

    - name: Push the first Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/api-add:latest

    - name: Build the second Docker image
      run: docker build ./celerytask --file ./celerytask/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/celery-add:latest

    - name: Push the second Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/celery-add:latest
